Repository AY2122S2-CS2103T-W13-2/tp, pull requests merged in 2022-03, with the labels that each got.

#72 Add Add_Class and Delete_Class Commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/address/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteClassCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tutorial/Day.java
  src/main/java/seedu/address/model/tutorial/Time.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
  src/main/java/seedu/address/model/tutorial/TutorialName.java
  src/main/java/seedu/address/model/tutorial/UniqueTutorialList.java
  src/main/java/seedu/address/model/tutorial/Venue.java
  src/main/java/seedu/address/model/tutorial/exceptions/TutorialNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.HIGH

#71 Add add_assessment and remove_assessment commands
  src/main/java/seedu/address/logic/commands/AddAssessmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAssessmentCommand.java
  src/main/java/seedu/address/logic/parser/AddAssessmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteAssessmentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assessment/Assessment.java
  src/main/java/seedu/address/model/assessment/AssessmentResults.java
  src/main/java/seedu/address/model/assessment/AssessmentResultsList.java
  src/main/java/seedu/address/model/assessment/UniqueAssessmentList.java
  src/main/java/seedu/address/model/assessment/Weightage.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
  src/main/java/seedu/address/model/tutorial/UniqueTutorialList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.HIGH

#74 Add List_Class Command
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/honganhcs.md
  docs/team/kev-intq.md
  docs/team/seanlaiys.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddClassCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListClassCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Displayable.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
  src/main/java/seedu/address/ui/DisplayListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TutorialCard.java
  src/main/resources/view/DisplayListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TutorialListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.HIGH

#76 Add add_student command
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/UniqueStudentsInTutorialList.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateStudentException.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
  src/main/java/seedu/address/model/tutorial/UniqueTutorialList.java
  src/main/java/seedu/address/model/tutorial/exceptions/InvalidTutorialException.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.HIGH

#82 Add storage for assessments and students
  src/main/java/seedu/address/storage/JsonAdaptedAssessment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: priority.HIGH

#90 Add Optional Day Field to List_Class Command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ListClassCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListClassCommandParser.java
  src/main/java/seedu/address/model/tutorial/TutorialHasSameDay.java
  src/main/resources/view/HelpCommandBox.fxml
  src/main/resources/view/HelpCommandDisplay.fxml
  src/main/resources/view/HelpCommandWindow.fxml
  src/main/resources/view/HelpWindow.fxml
Labels: priority.MEDIUM

#92 Add List_Students Comamnd with Optional Field Class
  src/main/java/seedu/address/logic/commands/ListStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListStudentCommandParser.java
  src/main/java/seedu/address/model/person/StudentHasTutorialNamePredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.MEDIUM

#98 Change add_score to grade, which allows adding or editing the score
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteAssessmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteClassCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/commands/ListScoreCommand.java
  src/main/java/seedu/address/logic/commands/ListStudentCommand.java
  src/main/java/seedu/address/logic/commands/RemoveStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddAssessmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddClassCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddStudentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteAssessmentCommandParser.java
  src/main/java/seedu/address/logic/parser/GradeCommandParser.java
  src/main/java/seedu/address/logic/parser/ListScoreCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemoveStudentCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/DisplayType.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assessment/AssessmentResults.java
  src/main/java/seedu/address/model/assessment/AssessmentResultsList.java
  src/main/java/seedu/address/model/assessment/Score.java
  src/main/java/seedu/address/model/assessment/StudentResult.java
  src/main/java/seedu/address/model/assessment/UniqueAssessmentList.java
  src/main/java/seedu/address/model/assessment/exceptions/StudentResultNotFound.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/StudentNotFoundException.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
  src/main/java/seedu/address/model/tutorial/UniqueTutorialList.java
  src/main/java/seedu/address/model/tutorial/exceptions/InvalidTutorialException.java
  src/main/java/seedu/address/ui/DisplayListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/StudentResultCard.java
  src/main/resources/view/StudentResultListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.HIGH

#96 Add add_score command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddScoreCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/RemoveStudentCommand.java
  src/main/java/seedu/address/logic/parser/AddScoreCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/DisplayType.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/assessment/AssessmentResults.java
  src/main/java/seedu/address/model/assessment/AssessmentResultsList.java
  src/main/java/seedu/address/model/assessment/Score.java
  src/main/java/seedu/address/model/assessment/StudentResult.java
  src/main/java/seedu/address/model/assessment/UniqueAssessmentList.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/person/exceptions/StudentNotFoundException.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
  src/main/java/seedu/address/model/tutorial/UniqueTutorialList.java
  src/main/java/seedu/address/model/tutorial/exceptions/InvalidTutorialException.java
  src/main/java/seedu/address/ui/DisplayListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/StudentResultCard.java
  src/main/resources/view/StudentResultListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.HIGH

#103 Add new FindByPrefix Command
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindByPrefixCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/DisplayType.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/NusNetId.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/StudentIdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/TutorialContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniqueFilteredPersonsList.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tutorial/TutorialName.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Story, priority.HIGH
